### ISSUE TITLE
How to set up PUBLIC_URL?

### ISSUE THREAD

**Issue by axelcostaspena** [sauravexodus/firestore-browser#1]
Hi.

I deployed your app with `firebase deploy` but it fails because of PUBLIC_URL variable not replaced.

All the instructions I found is to add an `.env` file for specifying the variable, and then compile with `npm run build`, and this creates a `/build/` directory with well compiled files but after deployment, the directory which is being served is the `/public/` one.

What to do?

Sorry for maybe not understanding the app.

**Comment by sauravexodus** [comment]
Hey @axelcostaspena,

The primary reason to build this app was the lack of querying capabilities on the firestore console online. Since they are already working on this feature, so I have stopped maintaining this project any further. 

This repository is not in a working state and I am going to archive it.

Thanks
